package com.wts.entity.model;

import com.wts.entity.base.BaseRecipe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recipe extends BaseRecipe<Recipe> {
	public static final Recipe dao = new Recipe().dao();
}
